name: artifact

on:
 push:
 workflow_dispatch:

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: step-security/harden-runner@v1
        with: 
          allowed-endpoints:
            95s5acprodeus1file6.blob.core.windows.net:443
            artifactcache.actions.githubusercontent.com:443
            github.com:443
            pipelines.actions.githubusercontent.com:443
      - uses: actions/cache@v2
        with:
          path: | 
            readme.md
          key: 'test'
      - run: nslookup host.docker.internal
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
      - uses: actions/download-artifact@v2
