name: create pr

on:      
 workflow_dispatch:

job:
  create-pr:
    steps:
      - uses: step-security@harden-runner@main
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
          git config user.name 'Varun'
          git config user.email 'varunsh-coder@users.noreply.github.com'
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
