name: IntegrationTest

on:
  workflow_dispatch:
    inputs:
      COMMIT_SHA:
        description: 'Commit SHA to be build'
        required: true
      REPO:
        description: 'Repo'
        required: true

permissions: read-all

jobs:
  integration-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      with:
        repository: ${{ github.event.inputs.REPO }}
        ref: ${{ github.event.inputs.COMMIT_SHA }}
         
    
    - name: Set up Go 
      uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4
      with:
        go-version: 1.17
    - run: go build -ldflags="-s -w" -o ./agent
    
