name: Lint
on:
  pull_request:
    branches: main
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest  
    steps:
      - uses: step-security/harden-runner@v1
        with:
          allowed-endpoints: 
            artifacts.codacy.com:443
      - uses: juliangruber/sleep-action@v1
        with:
          time: 130s
      - run: |
          curl -X GET https://artifacts.codacy.com
      - name: Publish to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        continue-on-error: true
